### ISSUE TITLE
`package_info_plus` still on version 4

### ISSUE THREAD

**Issue by martin-braun** [zeshuaro/google_api_headers#215]
According to #164 the `package_info_plus` version should be 5, but it's still on 4: https://github.com/zeshuaro/google_api_headers/blob/34d974f9586590021a21232fb4e3a5c404379c7d/pubspec.yaml#L13

Why? I maintain a package that uses `google_api_headers`, but I cannot update `package_info_plus` and my users want to use `package_info_plus` version 5, see https://github.com/martin-braun-net/google_maps_place_picker_mb/issues/73

Could you please release a new version with `package_info_plus` at `^5.0.0`?

**Comment by zeshuaro** [comment]
The PR you linked was reverted in #170 as the released version `5.0.0` was retracted a couple of days later. You can also see this from the changelog: https://pub.dev/packages/package_info_plus/changelog

Since pub.dev has a [policy](https://dart.dev/tools/pub/publishing#retract) to allow package to be retracted within 7 days, this repo won't update packages until they have been released for 7 days. 

But the latest version `5.0.1` was released 7 days ago, the Renovate bot (used to manage dependencies in this repo) should raise a PR soon to bump the version, which you can also see from the dashboard in #46.

**Comment by zeshuaro** [comment]
Closed by #217
