### ISSUE TITLE
unsupported kotlin gradle plugin version . please upgrade 

### ISSUE THREAD

**Issue by nowfalsalahudeen** [zeshuaro/google_api_headers#94]
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':google_api_headers' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10

**Comment by zeshuaro** [comment]
Hey @nowfalsalahudeen, any particular reason you decided to use the Kotlin plugin with v1.6.20 in your project? I'm asking because I just tried creating a new Flutter project with `flutter create` and it's still using v1.6.10 for the Kotlin plugin.

I would prefer to align with the version of a new Flutter project template if possible.
